# Copyright 2026 Agent ERP GmbH (https://www.agenterp.com)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl-3.0)
import hmac
import json
import logging

from markupsafe import escape

from odoo import SUPERUSER_ID, _, api, http

_logger = logging.getLogger(__name__)


class FinapiWebformController(http.Controller):
    """Handles the redirect back from finAPI and webhook callbacks."""

    @http.route(
        "/finapi/webform/return",
        type="http",
        auth="public",
        csrf=False,
        methods=["GET"],
    )
    def webform_return(self, **kwargs):
        """Landing page shown after the user finishes the finAPI Web Form.

        The user is told to close the tab and go back to the Odoo wizard.
        """
        return http.request.render(
            "account_statement_import_online_finapi.finapi_webform_return_template"
        )

    @http.route(
        "/finapi/webform/callback",
        type="http",
        auth="public",
        csrf=False,
        methods=["POST"],
    )
    def webform_callback(self, **kwargs):
        """Webhook endpoint for finAPI ``callbacks.finalised``.

        When a Web Form reaches a terminal state (COMPLETED, ABORTED, ...)
        finAPI POSTs a JSON payload here.  We look up the provider by
        ``finapi_last_webform_id`` and log the event.  The actual account
        linking still happens in the wizard (user must click "Refresh").

        Security: the callback URL registered at finAPI carries a shared
        secret as query parameter (``?secret=...``, generated by the
        wizard, stored in ``finapi.webhook_secret``). Requests without a
        valid secret are rejected.

        Payload example::

            {
                "webFormId": "...",
                "status": "COMPLETED",
                "payload": {"bankConnectionId": 123}
            }
        """
        # auth="public" gives us an initialised environment (public user)
        # without requiring a session; escalate to superuser for the config
        # lookup and the chatter note.
        env = api.Environment(http.request.env.cr, SUPERUSER_ID, {})

        expected_secret = (
            env["ir.config_parameter"].sudo().get_param("finapi.webhook_secret") or ""
        )
        provided_secret = kwargs.get("secret") or ""
        if not expected_secret or not hmac.compare_digest(
            provided_secret, expected_secret
        ):
            _logger.warning(
                "finAPI callback rejected: missing or invalid webhook secret"
            )
            return http.request.make_json_response(
                {"error": "forbidden"},
                status=403,
            )

        try:
            body = json.loads(http.request.httprequest.get_data(as_text=True))
        except (json.JSONDecodeError, TypeError):
            _logger.warning("finAPI callback: could not parse JSON body")
            return http.request.make_json_response(
                {"error": "invalid JSON"},
                status=400,
            )
        if not isinstance(body, dict):
            _logger.warning("finAPI callback: JSON body is not an object")
            return http.request.make_json_response(
                {"error": "invalid JSON"},
                status=400,
            )

        # Values come from an unauthenticated request — sanitise hard.
        webform_id = str(body.get("webFormId") or body.get("id") or "")[:64]
        status = str(body.get("status") or "UNKNOWN")[:50]
        _logger.info(
            "finAPI callback received: webFormId=%s status=%s",
            webform_id,
            status,
        )

        if webform_id:
            provider = env["online.bank.statement.provider"].search(
                [("finapi_last_webform_id", "=", webform_id)],
                limit=1,
            )
            if provider:
                provider.message_post(
                    body=_(
                        "finAPI Web Form callback: status=<b>%(status)s</b> "
                        "(webFormId=%(webform_id)s)"
                    )
                    % {
                        "status": escape(status),
                        "webform_id": escape(webform_id),
                    },
                    subject=_("finAPI Web Form callback"),
                )

        return http.request.make_json_response({"status": "ok"})
